# Оптимизированный конфиг PostgreSQL для VPS с 1GB RAM
listen_addresses = '*'
max_connections = 50

# Основные ограничения памяти (чтобы БД не убил OOM Killer)
shared_buffers = 128MB
work_mem = 4MB
maintenance_work_mem = 64MB
effective_cache_size = 256MB

# Настройки для PostGIS
jit = off # JIT иногда ест много памяти на простых гео-запросах
